language: python
python:
        - "3.5"
install:
        - pip install coverage
        - pip install coveralls
        - pip install -e . --use-mirrors
script:
        coverage run -m unittest discover

after_success:
        coveralls
